env:
  global:
  - CHKIT_VERSION=v3.2.0

install:
  - wget https://github.com/containerum/chkit/releases/download/${CHKIT_VERSION}/chkit_linux_amd64_${CHKIT_VERSION}.tar.gz
  - tar -zxf chkit_linux_amd64_${CHKIT_VERSION}.tar.gz && mv chkit /bin/chkit

script:
  - chkit get api
